### ISSUE TITLE
Question: Does this work for Mustang GTX amps?

### ISSUE THREAD

**Issue by teq0** [snhirsch/mustang-midi-bridge#9]
I'm assuming no, as they aren't mentioned anywhere.

**Comment by snhirsch** [comment]
I don't own a Mustang GT or GTX, but it's a safe bet that it won't be compatible.  Fender went out of their way to make poor design decisions on the newer amps.  You'd need a Bluetooth or Wifi sniffer to puzzle out the communication protocol.  I've long since moved on to a Kemper Profiler, so it won't be me doing the work.

**Comment by teq0** [comment]
Thanks.
